' Developer Express Code Central Example:
' How to load image tiles from another source
' 
' This example illustrates how to implement a custom map data provider class
' inherited from the MapDataProviderBase
' (http://help.devexpress.com/#WindowsForms/clsDevExpressXtraMapMapDataProviderBasetopic)
' type.
' 
' You can find sample updates and versions for different programming languages here:
' http://www.devexpress.com/example=E4758
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18052
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Namespace CustomProvider.Properties

    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")>
    Friend NotInheritable Partial Class Settings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As CustomProvider.Properties.Settings = CType((Global.System.Configuration.ApplicationSettingsBase.Synchronized(New CustomProvider.Properties.Settings())), CustomProvider.Properties.Settings)

        Public Shared ReadOnly Property [Default] As Settings
            Get
                Return CustomProvider.Properties.Settings.defaultInstance
            End Get
        End Property
    End Class
End Namespace
